apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.port.ingressPort }}
    targetPort: {{ .Values.port.appPort }}
  selector:
    app: {{ .Release.Name }}
